<?php $randomPlayerList = rand(0, 10000); ?>
<?php $randomPlugins = rand(0, 10000); ?>
<?php echo $args['before_widget']; ?>
<?php echo $args['before_title'] . $instance['title'] . $args['after_title']; ?>
<p>
    <?php if (isset($instance['show_status']) && $instance['show_status'] == 'on'): ?>
    Status: <span style="color:red;font-weight:bold">Hors ligne</span><br>
    <?php endif; ?>

    <?php if (isset($instance['show_host']) && $instance['show_host'] == 'on'): ?>
    Hôte: <strong><?php echo $instance['host']; ?></strong><br>
    <?php endif; ?>

    <?php if (isset($instance['show_port']) && $instance['show_port']): ?>
    Port: <strong><?php echo $instance['port']; ?></strong><br>
    <?php endif; ?>
</p>

<?php echo $args['after_widget']; ?>
